version: "3.8"
services:
  postgres:
    image: postgres:16
    container_name: pokemon-db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pokemon
    ports:
      - "5432:5432"
    volumes:
      - pokemon-data:/var/lib/postgresql/data

volumes:
  pokemon-data:
